MODEL:
  NAME: 'apn'
  DIST: 'dot'
  BACKBONE:
    NAME: 'resnet101'
    CKPT_PATH: 'checkpoints/resnet101_ft_CUB.pt'
  IMAGE_SIZE: 448
  LOSSES:
    L_CLS: 1
    L_REG: 0.1
    L_CPT: 0.2
DATASET:
  NAME: "CUB"
  NUM_CLASSES: 200
  NUM_ATTRS: 312
  ROOT_DIR: "datasets"
OPTIM:
  LR: 5e-3
  EPOCHS: 60
  BATCH_SIZE: 16
  STEP_SIZE: 30
  GAMMA: 0.5
SEED: 42