MODEL:
  NAME: 'apn'
  DIST: 'dot'
  BACKBONE:
    NAME: 'resnet101'
    CKPT_PATH: 'checkpoints/resnet101_ft_CUB.pt'
  IMAGE_SIZE: 224
  LOSSES:
    L_CLS: 1
    L_REG: 0.01
    # L_CPT: 0.0
DATASET:
  NAME: "CUB"
  NUM_CLASSES: 200
  NUM_ATTRS: 312
  TRANSFORMS: 'resnet101'
  ROOT_DIR: "datasets"
OPTIM:
  LR: 1e-4  # official implementation uses 1e-3
  EPOCHS: 30
  BATCH_SIZE: 64  # official implementation uses 64
  STEP_SIZE: 10
  BETA1: 0.5
  BETA2: 0.999
  GAMMA: 0.5
SEED: 42

