MODEL:
  NAME: 'apn'
  DIST: 'dot'
  BACKBONE:
    NAME: 'resnet101'
    CKPT_PATH: 'checkpoints/resnet101_ft_CUB.pt'
  IMAGE_SIZE: 224
  LOSSES:
    L_CLS: 1
    L_REG: 1
    L_CPT: 0.2
DATASET:
  NAME: "CUB"
  NUM_CLASSES: 200
  NUM_ATTRS: 107
  ROOT_DIR: "datasets"
OPTIM:
  LR: 1e-3
  EPOCHS: 30
  BATCH_SIZE: 16
  STEP_SIZE: 10
  GAMMA: 0.5
SEED: 42