MODEL:
  NAME: 'resnet101'
  IMAGE_SIZE: 224
DATASET:
  NAME: "CUB"
  NUM_CLASSES: 200
  ROOT_DIR: "datasets"
  TRANSFORMS: "resnet101"
OPTIM:
  LR: 1e-4
  EPOCHS: 20
  BATCH_SIZE: 32
  STEP_SIZE: 5
  GAMMA: 0.5
SEED: 42
