MODEL:
  NAME: 'resnet101'
  IMAGE_SIZE: 448
DATASET:
  NAME: "CUB"
  NUM_CLASSES: 200
  NUM_ATTRS: 107
  ROOT_DIR: "datasets"
OPTIM:
  LR: 1e-3
  EPOCHS: 20
  BATCH_SIZE: 16
  STEP_SIZE: 10
  GAMMA: 0.5
SEED: 42
